#!/usr/bin/env sh

##
# Usage
#
# Start a FAD-1234 branch (off master by default)
# $ git start FAD-1234
#
# Start a FAD-1234 branch off master, as specified
# $ git start FAD-1234 master
#
##

# exit on error
set -e

if [[ $1 = '' ]]; then
  echo "Please specify a name (e.g. FAD-1234)"
  exit 255
fi

BRANCH='master'
[[ $2 != '' ]] && BRANCH=$2

git checkout $BRANCH
git pull origin $BRANCH
git checkout -b $1
