#!/usr/bin/env sh

##
# Usage
#
# Start a FAD-1234 branch (off repo default branch by default)
# $ git start FAD-1234
#
# Start a FAD-1234 branch off main, as specified
# $ git start FAD-1234 main
#
##

# exit on error
set -e

if [[ $1 = '' ]]; then
  echo "Please specify a name (e.g. FAD-1234)"
  exit 255
fi

BRANCH=`git remote show origin | grep "HEAD branch" | awk '{print $3}'`
[[ $2 != '' ]] && BRANCH=$2

git checkout $BRANCH
git pull origin $BRANCH
git checkout -b $1
