#!/usr/bin/env bash

##
# Usage
#
# Updates current branch:
# $ git update
#
# Updates with rebase rather than merge
# $ git update rebase
##

git fetch > /dev/null 2>&1

# exit on error
set -e

BRANCH=$(git rev-parse --abbrev-ref HEAD)
TYPE=$1


if [[ $BRANCH = 'master' ]]; then
  echo "you can't update master silly"
  exit 255
fi

git fetch  # get new stuff

if [[ $TYPE = 'rebase' ]]; then
  git rebase origin/master
else
  git merge origin/master
fi

