#!/usr/bin/env sh

set -e

CMD=$1
GREEN='\033[0;32m'
BLUE='\033[0;36m'
NOCOLOR='\033[0m'

# $ git plus upgrade
# upgrades to latest version of gitplus
if [[ "$CMD" == "upgrade" ]]; then
  # cd $(echo $PATH | tr ":" "\n" | grep gitplus)
  cd $(dirname $0)
  git checkout main --quiet
  git diff origin/main
  git pull origin main --quiet
  echo "\n${GREEN}👍  your gitplus is up to date with the latest from origin/main${NOCOLOR}\n"
fi

ECHOBLUE=`echo ${BLUE}`
ECHONC=`echo ${NOCOLOR}`

if [[ "$CMD" == "help" ]]; then
  cat $(dirname $0)/../README.md | sed -e "s/#\{2,5\} \(.*\)/$ECHOBLUE\1$ECHONC/"
fi
