#!/usr/bin/env sh

##
# Usage
#
# Start a hotfix/FAD-1234 branch (off master by default)
# $ git start hotfix FAD-1234
#
# Start a feature/FAD-1234 branch (off develop by default)
# $ git start feature FAD-1234
#
# Start a whatever/FAD-1234 branch off master, as specified
# $ git start whatever FAD-1234 master
#
##

if [[ $1 = '' || $2 = '' ]]; then
  echo "Please specify a type (ie hotfix) and name (ie FAD-1234)"
  exit 255
fi

[[ $1 = 'hotfix' ]] && BRANCH='master' || BRANCH='develop'
[[ $3 != '' ]] && BRANCH=$3

git checkout -b $1/$2 $BRANCH
