#!/usr/bin/env sh

##
# Usage
#
# Finish current branch based on its name:
# $ git finish
#
# Finish current branch with hotfix strategy
# $ git finish hotfix
#
# Finish current branch and also push merged branch(es) to origin
# $ git finish [hotfix] push
#
##

BRANCH=$(git rev-parse --abbrev-ref HEAD)
TYPE=$1

if [[ $BRANCH = 'master' || $BRANCH = 'develop' ]]; then
  echo "ugh don't finish $BRANCH"
  exit 255
fi

if [[ $TYPE = 'hotfix' || ${BRANCH:0:7} = "hotfix/" ]]; then
  git checkout master || exit 255
  git merge --no-ff $BRANCH || exit 255
  [[ $1 = 'push' || $2 = 'push' ]] && git push origin master
fi

git checkout develop || exit 255
git merge --no-ff $BRANCH || exit 255
[[ $1 = 'push' || $2 = 'push' ]] && git push origin develop
